language: go
go: 1.4

before_script:
 - go get -v github.com/tbaczynski/powerdns_exporter

script:
 - go build -a -v github.com/tbaczynski/powerdns_exporter/...
 - go test -v github.com/tbaczynski/powerdns_exporter/...
